# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=false

# Gradle Plugin Versions
	fabric_loom_version=1.7-SNAPSHOT
	forge_gradle_version=[6.0.24,6.2)
	neoforge_gradle_version=7.0.150

# Mod Dependencies
	ichunutil_version=1.0.0
	ichunutil_version_range=[1.0.0,)

# Mod Properties
	mod_id = ding
	mod_name = Ding
	mod_description = Plays a sound once the client has loaded to the main menu, a server, or resources
	maven_group = me.ichun.mods
	archives_base_name = Ding
	mod_license = GNU Lesser General Public License v3.0

# Mod Links
	mod_url_home = https://www.curseforge.com/members/ohaiichun/projects
	mod_url_sources = https://github.com/iChun/Ding
	mod_url_issues = https://github.com/iChun/Ding/issues
	mod_url_discord = https://discord.gg/wvxVkmpt3g

# Publishing Info
	modrinth_project_id=UEtTD3gP
	curseforge_project_id_forge=231275
	curseforge_project_id_fabric=822694
	curseforge_environment=client